void MenuComp();
void AjouterComp();
void RechercheComp();
void SupprimerComp();
void ModifierComp();
int RechercheCompParNom(char * );
int rechComp(int );
void AfficherComp();
int getIDComp(char *);
int SaisirCV();
