void AjoutertTC();
void RechercheTC();
void SupprimerTC();
void ModifierTC();
void AfficherTC();
void MenuTypeContrat();
int rechTC(int );
void AfficherTCE(int );
int RechercheTCParNom(char *);
int getIDTypecontrat(char *);
